# Basics of NumPy and Pandas

####  Author - Rithik K.

# Numpy - Numeric Python

- Numpy supports array whichis faster than list and other sequence.

- The main data structure in numpy is ndarray (n- dimentions), homogeneous, multidimension array. 

- Numpy array can be created from list, tuple or other sequence or by using build in functions.

- Numpy is essential library for numerical computing in python.

In [1]:
import warnings

warnings.filterwarnings("ignore")

In [2]:
pip install numpy

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.4'

In [5]:
arr = np.array([1,3,4,5,2.3])
arr

array([1. , 3. , 4. , 5. , 2.3])

In [6]:
arr1 = np.array([1,2,3,4,5,2.3,'a'])
arr1

array(['1', '2', '3', '4', '5', '2.3', 'a'], dtype='<U32')

In [7]:
arr2 = np.array(24)
arr2.ndim             # dimentions of aaray

0

In [8]:
arr1.ndim

1

#### reshape()

In [9]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [10]:
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr3.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
arr3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
arr3.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
arr3.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

#### zeros()

In [15]:
arr4 = np.zeros(9)
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
arr5 = np.zeros([3,4],dtype = 'int')
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
arr6 = np.zeros([3,4,5],dtype = 'int')
arr6

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

#### ones()

In [18]:
arr7 = np.ones(9)
arr7

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
arr8 = np.ones([3,4],dtype = 'int')
arr8

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
arr9 = np.ones([3,4,5],dtype = 'int')
arr9

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

####  empty()

In [21]:
arr10 = np.empty(10)
arr10

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [22]:
arr11 = np.empty([3,3])
arr11

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr12 = np.empty([3,4,5])
arr12

array([[[1.16609559e-311, 1.16607362e-311, 4.00234433e-312,
         0.00000000e+000, 1.69484279e-319],
        [4.00234433e-312, 0.00000000e+000, 1.16610553e-311,
         0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.16610561e-311, 1.97626258e-323,
         6.95178866e-310, 2.02369289e-320],
        [1.97626258e-323, 6.95178866e-310, 9.88131292e-324,
         0.00000000e+000, 0.00000000e+000]],

       [[1.67966509e-318, 0.00000000e+000,             nan,
         0.00000000e+000, 4.67296746e-307],
        [1.69121096e-306, 1.86921822e-306, 1.42413555e-306,
         1.78019082e-306, 1.37959740e-306],
        [6.23057349e-307, 1.02360935e-306, 1.69120416e-306,
         1.78022342e-306, 6.23058028e-307],
        [1.06811422e-306, 1.39071445e-307, 8.01097889e-307,
         1.78020169e-306, 7.56601165e-307]],

       [[1.02359984e-306, 8.90092016e-307, 1.02361342e-306,
         6.89804133e-307, 8.90104239e-307],
        [8.90098127e-307, 8.90111708e-307, 6.23054633e-307,


#### arange()

In [24]:
arr13 = np.arange(10,21)
arr13

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
arr14 = np.arange(30,20,-1)
arr14

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [26]:
arr15 = np.arange(10,20)
arr15.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

####  eye()

In [27]:
arr16 = np.eye(3,5,dtype = 'int')
arr16

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [28]:
arr17 = np.eye(10,10,dtype = 'int')
arr17

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

#### identity()

In [29]:
arr18 = np.identity(7,dtype = 'int')
arr18

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

#  random

- rand()
- randint()
- randn()

####  random.rand()       

In [30]:
arr = np.random.rand(10) #return random values between 0 and 1
arr

array([0.80188507, 0.98738195, 0.15334391, 0.27243593, 0.98753582,
       0.44162683, 0.40417609, 0.14768865, 0.83251058, 0.99833284])

####  random.randint()

In [31]:
arr = np.random.randint(10,30,7)  #return array of random values between given range
arr

array([10, 12, 15, 29, 17, 19, 23])

#### random.randn()

In [32]:
arr = np.random.randn(6)  #return the random normally distributed
arr

array([ 0.031015  ,  0.48129794, -1.17481132, -0.86832059,  0.33473906,
       -0.7786428 ])

In [33]:
import warnings

warnings.filterwarnings('ignore')

## 1. Mean

In [34]:
arr = np.array([12,34,2,1,33,4,55
                ,32,11,66,88,78,90])

In [35]:
sum(arr)/len(arr)

38.92307692307692

In [36]:
mean1 = np.mean(arr)
mean1

38.92307692307692

## 2. Median 

In [37]:
arr = np.array([12,34,2,1,33,4,55
                ,32,11,66,88,78,90])

In [38]:
median1 = np.median(arr)
median1

33.0

## 3. Mode

In [39]:
arr = np.array([12,34,2,1,33,4,55
                ,32,11,66,88,78,90,4,11,32,4,12,11])

In [40]:
mode1 = np.mode(arr)
mode1                # To find mode we have to use scipy library instead of numpy

AttributeError: module 'numpy' has no attribute 'mode'

In [41]:
from scipy import stats

In [42]:
mode1 = stats.mode(arr)
mode1

ModeResult(mode=array([4]), count=array([3]))

In [43]:
arr1 = np.array([[2,3,4],[4,6,7],[6,6,7]])

mode2 = stats.mode(arr1)
mode2

ModeResult(mode=array([[2, 6, 7]]), count=array([[1, 2, 2]]))

## Variance

In [44]:
var = np.var(arr)
var

873.7229916897505

## Standard Deviation

In [45]:
var1 = np.var(arr)

In [46]:
np.sqrt(var1)

29.55880565397984

In [47]:
std = np.std(arr)
std

29.55880565397984

## ceil  

In [48]:
np.ceil(0.3)    #returns nearest highest integer

1.0

In [49]:
np.ceil(7.0)

7.0

## floor

In [50]:
np.floor(2.33) # return nearest lowest integer


2.0

In [51]:
np.floor(4.9)

4.0

#  Pandas

- It is a open source library.
- Pandas mainly used for working with relational or labelled data.
- It provides various data structure and operations for manipulating data.
- Pandas support 2 datastructures.
                 1. Series.
                 2. DataFrame.
- This data structure is mutable in nature.
- Pandas DataFrame can be using dictionary, csv, Excel, database, etc.
- Using pandas we can store hetrogeneous tabular data.

In [52]:
pip install pandas

In [53]:
import pandas as pd
import numpy as np

####  DataFrame

- In pandas DataFrame is a 2 dimentional data structure, like 2d array or table with rows and colunms.

                                             Syntax: 
                                                     pd.DataFrame()

In [54]:
data = {'A':[10,20,30,40,50,60,70],'B':[20,30,40,50,60,70,80]}
df = pd.DataFrame(data)
df

A   B
0  10  20
1  20  30
2  30  40
3  40  50
4  50  60
5  60  70
6  70  80

In [55]:
data1 = np.arange(1,21).reshape(5,4)

data1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [56]:
df1 = pd.DataFrame(data1,index = ['r1','r2','r3','r4','r5'],columns = ['c1','c2','c3','c4'])
df1

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20

In [57]:
type(df1['c1'])

pandas.core.series.Series

### Series

- It is one dimentional array holding data of any type. 
- In pandas series is like a single column in table or single row in table.

                                Syntax:
                                       
                                        pd.Series(data Collection)

In [58]:
list1 = [1,2,3,4,5]

In [59]:
s1 = pd.Series(list1)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [60]:
type(s1)

pandas.core.series.Series

## Read File in DataFrame

In [61]:
pip install openpyxl

In [62]:
df1 = pd.read_excel('Tennis_dataset.xlsx')

In [63]:
df1

Outlook  Temp Humidity    Wind Play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [64]:
df2 = pd.read_csv('Iris.csv')
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [65]:
df3 = pd.read_csv('Data.csv')
df3

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

####  Accessing Rows and Columns

- By using slicing.
- Row index - loc (using location)
- Row index, Column index, - iloc (indexbased selectionof rows and columns)

#####  Q. What is difference between loc and iloc function ?

####  By Slicing

In [66]:
df2[70:81]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
70  71            5.9           3.2            4.8           1.8   
71  72            6.1           2.8            4.0           1.3   
72  73            6.3           2.5            4.9           1.5   
73  74            6.1           2.8            4.7           1.2   
74  75            6.4           2.9            4.3           1.3   
75  76            6.6           3.0            4.4           1.4   
76  77            6.8           2.8            4.8           1.4   
77  78            6.7           3.0            5.0           1.7   
78  79            6.0           2.9            4.5           1.5   
79  80            5.7           2.6            3.5           1.0   
80  81            5.5           2.4            3.8           1.1   

            Species  
70  Iris-versicolor  
71  Iris-versicolor  
72  Iris-versicolor  
73  Iris-versicolor  
74  Iris-versicolor  
75  Iris-versicolor  
76  Iris-versicolor  
77  Iris-versicolor  
78  Iris-versicolor  
79  Iris-versicolor  
80  Iris-versicolor

In [67]:
df2[['SepalWidthCm','PetalLengthCm','Species']]

SepalWidthCm  PetalLengthCm         Species
0             3.5            1.4     Iris-setosa
1             3.0            1.4     Iris-setosa
2             3.2            1.3     Iris-setosa
3             3.1            1.5     Iris-setosa
4             3.6            1.4     Iris-setosa
..            ...            ...             ...
145           3.0            5.2  Iris-virginica
146           2.5            5.0  Iris-virginica
147           3.0            5.2  Iris-virginica
148           3.4            5.4  Iris-virginica
149           3.0            5.1  Iris-virginica

[150 rows x 3 columns]

####  By Using location

In [68]:
df2.loc[70:80,'SepalWidthCm':'Species']

SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
70           3.2            4.8           1.8  Iris-versicolor
71           2.8            4.0           1.3  Iris-versicolor
72           2.5            4.9           1.5  Iris-versicolor
73           2.8            4.7           1.2  Iris-versicolor
74           2.9            4.3           1.3  Iris-versicolor
75           3.0            4.4           1.4  Iris-versicolor
76           2.8            4.8           1.4  Iris-versicolor
77           3.0            5.0           1.7  Iris-versicolor
78           2.9            4.5           1.5  Iris-versicolor
79           2.6            3.5           1.0  Iris-versicolor
80           2.4            3.8           1.1  Iris-versicolor

#### By Using iloc 

In [69]:
df2.iloc[100:141,1:4]

SepalLengthCm  SepalWidthCm  PetalLengthCm
100            6.3           3.3            6.0
101            5.8           2.7            5.1
102            7.1           3.0            5.9
103            6.3           2.9            5.6
104            6.5           3.0            5.8
105            7.6           3.0            6.6
106            4.9           2.5            4.5
107            7.3           2.9            6.3
108            6.7           2.5            5.8
109            7.2           3.6            6.1
110            6.5           3.2            5.1
111            6.4           2.7            5.3
112            6.8           3.0            5.5
113            5.7           2.5            5.0
114            5.8           2.8            5.1
115            6.4           3.2            5.3
116            6.5           3.0            5.5
117            7.7           3.8            6.7
118            7.7           2.6            6.9
119            6.0           2.2            5.0
120            6.9           3.2            5.7
121            5.6           2.8            4.9
122            7.7           2.8            6.7
123            6.3           2.7            4.9
124            6.7           3.3            5.7
125            7.2           3.2            6.0
126            6.2           2.8            4.8
127            6.1           3.0            4.9
128            6.4           2.8            5.6
129            7.2           3.0            5.8
130            7.4           2.8            6.1
131            7.9           3.8            6.4
132            6.4           2.8            5.6
133            6.3           2.8            5.1
134            6.1           2.6            5.6
135            7.7           3.0            6.1
136            6.3           3.4            5.6
137            6.4           3.1            5.5
138            6.0           3.0            4.8
139            6.9           3.1            5.4
140            6.7           3.1            5.6

In [70]:
df2.iloc[60:66,:3]

Id  SepalLengthCm  SepalWidthCm
60  61            5.0           2.0
61  62            5.9           3.0
62  63            6.0           2.2
63  64            6.1           2.9
64  65            5.6           2.9
65  66            6.7           3.1

In [71]:
df2.iloc[80:91,-2:]

PetalWidthCm          Species
80           1.1  Iris-versicolor
81           1.0  Iris-versicolor
82           1.2  Iris-versicolor
83           1.6  Iris-versicolor
84           1.5  Iris-versicolor
85           1.6  Iris-versicolor
86           1.5  Iris-versicolor
87           1.3  Iris-versicolor
88           1.3  Iris-versicolor
89           1.3  Iris-versicolor
90           1.2  Iris-versicolor

In [72]:
df3

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

## Basic important functions in pandas

- head()
- tail()
- info()
- describe()
- shape

In [73]:
df2.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [74]:
df2.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [75]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [76]:
df2.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [77]:
df2.shape

(150, 6)

### Add and Delete the rows and column in DataFrame

- To add data in rows we have to use "loc" function.

In [78]:
df2.loc[150] = [150,5.8,3.2,5.4,2.0,'Iris-virginica']
df2.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150  Iris-virginica

In [79]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 151 entries, 0 to 150
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             151 non-null    int64  
 1   SepalLengthCm  151 non-null    float64
 2   SepalWidthCm   151 non-null    float64
 3   PetalLengthCm  151 non-null    float64
 4   PetalWidthCm   151 non-null    float64
 5   Species        151 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 8.3+ KB


### To add column in DataFrame we have to use column indexing

In [80]:
df2['new_col'] = np.arange(1,152)

In [81]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 151 entries, 0 to 150
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             151 non-null    int64  
 1   SepalLengthCm  151 non-null    float64
 2   SepalWidthCm   151 non-null    float64
 3   PetalLengthCm  151 non-null    float64
 4   PetalWidthCm   151 non-null    float64
 5   Species        151 non-null    object 
 6   new_col        151 non-null    int32  
dtypes: float64(4), int32(1), int64(1), object(1)
memory usage: 8.8+ KB


In [82]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  
150  Iris-virginica      151  

[151 rows x 7 columns]

In [83]:
df2['SepalCm'] = df2['SepalLengthCm'] + df2['SepalWidthCm']

df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  SepalCm  
0       Iris-setosa        1      8.6  
1       Iris-setosa        2      7.9  
2       Iris-setosa        3      7.9  
3       Iris-setosa        4      7.7  
4       Iris-setosa        5      8.6  
..              ...      ...      ...  
146  Iris-virginica      147      8.8  
147  Iris-virginica      148      9.5  
148  Iris-virginica      149      9.6  
149  Iris-virginica      150      8.9  
150  Iris-virginica      151      9.0  

[151 rows x 8 columns]

### To delete the rows and columns in DataFrame

- Using Drop() method

- Delete Column

In [84]:
df2.drop('SepalCm',axis = 1)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  
150  Iris-virginica      151  

[151 rows x 7 columns]

In [85]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  SepalCm  
0       Iris-setosa        1      8.6  
1       Iris-setosa        2      7.9  
2       Iris-setosa        3      7.9  
3       Iris-setosa        4      7.7  
4       Iris-setosa        5      8.6  
..              ...      ...      ...  
146  Iris-virginica      147      8.8  
147  Iris-virginica      148      9.5  
148  Iris-virginica      149      9.6  
149  Iris-virginica      150      8.9  
150  Iris-virginica      151      9.0  

[151 rows x 8 columns]

In [86]:
df2.drop('SepalCm',axis = 1, inplace = True)

In [87]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  
150  Iris-virginica      151  

[151 rows x 7 columns]

- Delete Row

In [88]:
df2.drop(150,axis = 0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
145  Iris-virginica      146  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  

[150 rows x 7 columns]

In [89]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   
150  150            5.8           3.2            5.4           2.0   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  
150  Iris-virginica      151  

[151 rows x 7 columns]

In [90]:
df2.drop(150,axis = 0,inplace = True)

In [91]:
df2

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  new_col  
0       Iris-setosa        1  
1       Iris-setosa        2  
2       Iris-setosa        3  
3       Iris-setosa        4  
4       Iris-setosa        5  
..              ...      ...  
145  Iris-virginica      146  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  

[150 rows x 7 columns]

In [92]:
df2.drop(np.arange(1,21),axis = 0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
21    22            5.1           3.7            1.5           0.4   
22    23            4.6           3.6            1.0           0.2   
23    24            5.1           3.3            1.7           0.5   
24    25            4.8           3.4            1.9           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  new_col  
0       Iris-setosa        1  
21      Iris-setosa       22  
22      Iris-setosa       23  
23      Iris-setosa       24  
24      Iris-setosa       25  
..              ...      ...  
145  Iris-virginica      146  
146  Iris-virginica      147  
147  Iris-virginica      148  
148  Iris-virginica      149  
149  Iris-virginica      150  

[130 rows x 7 columns]